import { createContext, useContext, useEffect, useState } from 'react';

const LanguageContext = createContext();

const translations = {
  tr: {
    // Menü
    menuDashboard: 'Panel',
    menuTracker: 'Başvurularım',
    menuAgenda: 'Ajanda',
    menuCalendar: 'Takvim',
    menuDev: 'Gelişim',
    menuResume: 'Özgeçmiş',
    
    // Dashboard (İstatistikler)
    statTotal: 'Başvurulan',
    statInterview: 'Mülakat',
    statAssessment: 'Teknik Sınav',
    statVideo: 'Video Mülakat',
    statOffer: 'Kabul',
    calendarTitle: 'Takvim',
    reminderTitle: 'Hatırlatıcı',
    dashStreak: 'Günlük Seri',
    dashStreakMsg: 'Seriyi bozmamak için yarın da gel!',
    dashNoEvent: 'Bugün planlanan bir etkinlik yok. Sakin bir gün! ☕',

    // Topbar
    myAccount: 'HESABIM',
    loggedInAs: 'GİRİŞ YAPILAN HESAP',
    profile: 'Profilim',
    settings: 'Ayarlar',
    logout: 'Çıkış Yap',
    comingSoon: 'Bu özellik yakında eklenecek!',
    defaultUser: 'Kullanıcı',
    
    // Karşılama Sayfası
    navHome: 'Ana Sayfa',
    navAbout: 'Hakkında',
    navBlog: 'Blog',
    navContact: 'İletişim',
    navRegister: 'Kayıt Ol',
    navLogin: 'Giriş Yap',
    heroTitlePart1: 'Minik Adımlar, ',
    heroTitleHighlight: 'Büyük Hayaller.',
    heroSubtitle: 'İş başvurularını, mülakatlarını, eğitimlerini ve tüm kariyer süreçlerini tek bir yerden, stressiz ve düzenli bir şekilde takip et.',
    getStartedBtn: 'Hemen Başla 🚀',
    aboutTitle: 'Pebble Nedir?',
    aboutText: 'Pebble, iş arama ve kariyer gelişimi sürecindeki o karmaşık ve stresli dönemi, pofuduk ve düzenli bir serüvene dönüştüren akıllı bir takip sistemidir. Başvurularını bir tabloya hapsetmek yerine; mülakatlarını, takvimini ve notlarını tek bir canlı ekranda birleştirir.',
    blogTitle: 'Kariyer Blogu',
    blogText: 'Mülakat taktikleri, özgeçmiş hazırlama sırları ve kariyerine yön verecek harika ipuçları çok yakında burada olacak!',
    contactTitle: 'Bize Ulaşın',
    contactText: 'Bir sorun mu var? Veya sadece selam mı vermek istiyorsun? Pebble ekibi olarak mesajlarını sabırsızlıkla bekliyoruz.',

    // Kayıt (Register) Sayfası
    regTitle: 'Aramıza Katıl ✨',
    regFirstName: 'Ad',
    regLastName: 'Soyad',
    regEmail: 'Mail',
    regPassword: 'Şifre',
    regConfirmPassword: 'Şifreyi Tekrar Gir',
    regBtn: 'Kayıt Ol',
    regHasAccount: 'Hesabın var mı? Giriş Yap',
    msgRegSuccess: 'Kayıt Başarılı! 🎉',
    msgEmailInUse: 'Bu mail zaten kullanımda! Giriş yap.',
    msgPassMismatch: 'Şifreler eşleşmiyor!',
    msgRegFailed: 'Kayıt Başarısız!',
    msgPassRules: 'Lütfen şifre kurallarına uyun!',
    passRulesTitle: 'Şifre Kuralları:',
    passRule1: 'En az 8 karakter uzunluğunda olmalı.',
    passRule2: 'En az bir büyük harf ve bir rakam içermeli.',
    passRule3: 'En az bir özel karakter (!@#$ vb.) içermeli.',

    // Giriş (Login) Sayfası
    loginTitle: 'Hoş Geldin ✨',
    loginBtn: 'Giriş Yap',
    forgotPass: 'Şifremi Unuttum',
    loginOr: 'VEYA',
    loginGoogle: 'Google ile Giriş Yap',
    loginNoAccount: 'Hesabın yok mu? Kayıt Ol',
    msgLoginFailed: 'Giriş Başarısız! Bilgilerini kontrol et.',
    msgLoginSuccess: 'Giriş Başarılı! Yönlendiriliyorsun...',
    
    // Şifremi Unuttum Modalı
    forgotPassTitle: 'Şifreni mi Unuttun? 🥺',
    forgotPassDesc: 'Merak etme, yeni şifreni belirleyip eski verilerine kavuşabilirsin.',
    forgotNewPass: 'Yeni Şifre',
    forgotConfirmPass: 'Yeni Şifre (Tekrar)',
    btnResetPass: 'Şifremi Güncelle',
    msgPassResetSuccess: 'Şifren başarıyla güncellendi! 🎉',

    // Tracker Tablo
    dashTitle: 'Başvurularım',
    dashSubtitle: 'Kariyer yolculuğundaki tüm adımların burada ✨',
    addNew: '+ Yeni Ekle',
    loading: 'YÜKLENİYOR...',
    emptyList: 'Henüz bir kayıt yok. Kariyer serüvenine başla!',
    colCompany: 'KURUM',
    colPosition: 'POZİSYON',
    colLocMode: 'LOKASYON & MOD',
    colSalary: 'MAAŞ',
    colStage: 'AŞAMA',
    colAction: 'İŞLEM',
    btnView: 'Görüntüle',
    unspecified: 'Belirtilmedi',
    
    // Uyarılar ve Başvuru Durumları
    confirmDelete: 'Bu işlemi gerçekleştirmek istediğine emin misin?',
    errorLog: 'Hata',
    userInfoError: 'Kullanıcı bilgisi alınamadı',
    statusApplied: 'Başvuruldu',
    statusAssessment: 'Teknik Sınav',
    statusVideo: 'Video Mülakat',
    statusInterview: 'Görüşme',
    statusOffer: 'Kabul',
    statusRejected: 'Red',

    // Modallar Ortak
    btnCancel: 'İptal',
    btnSave: 'Kaydet',
    btnUpdating: 'Güncelleniyor...',

    // Form Modalı
    newAppTitle: 'Yeni Başvuru Kaydı',
    formCompany: 'Kurum / Şirket Adı',
    formPosition: 'Pozisyon / Program Adı',
    formCategory: 'Kategori',
    catJob: 'İş Başvurusu',
    catInternship: 'Staj',
    catBootcamp: 'Bootcamp',
    catWebinar: 'Webinar',
    catOther: 'Diğer',
    formPlatform: 'Platform',
    platCompanySite: 'Şirket Sitesi',
    platOther: 'Diğer (URL/Ad Belirt)',
    platPlaceholder: 'Site adı veya URL...',
    formSalaryStatus: 'Maaş / Ücret Durumu',
    salUnknown: 'Bilinmiyor',
    salVolunteer: 'Gönüllü (Ücretsiz)',
    salSpecific: 'Tutar Belirt...',
    formAmount: 'Miktar',
    salPlaceholder: 'Örn: 45.000 TL',
    formWorkMode: 'Çalışma Modeli',
    modeRemote: 'Remote',
    modeHybrid: 'Hybrid',
    modeOnsite: 'Ofis',
    formLocation: 'Lokasyon',
    locPlaceholder: 'Şehir/Ülke',
    formDate: 'Tarih',
    formQuestions: 'Başvuru Formu Soruları & Cevaplarım',
    questionsPlaceholder: 'Deneyim yılı, teknik sorular vb. formda ne cevap verdiğini buraya not et...',
    formDescription: 'İlan Detayları',
    descPlaceholder: 'İş tanımını buraya yapıştırabilirsin...',

    // Detay Modalı
    oldNote: 'Eski Not',
    detailPlatform: 'Platform',
    detailUnspecified: 'Belirsiz',
    detailSalary: 'Maaş',
    detailMode: 'Mod',
    detailLocation: 'Lokasyon',
    detailNotSpecified: 'Belirtilmedi',
    detailQuestions: 'Başvuru Formu Bilgilerim',
    detailDescription: 'İş Tanımı',
    detailJournal: 'Süreç Günlüğü',
    journalPlaceholder: 'Bu aşamada neler oldu? Notlarını ekle...',
    btnAddJournal: 'Günlüğe Ekle',
    emptyJournal: 'Henüz bir günlük girişi yapılmamış.',

    // Statü Modalı
    statusUpdating: 'Aşama Güncelleniyor',
    newStatusLabel: 'Yeni statü:',
    statusNotePrompt: 'Bu değişiklikle ilgili bir not eklemek ister misin?',
    statusNotePlaceholder: 'Örn: Teknik sınav maili geldi, haftaya Salı günü için randevulaştık...',
    btnUpdateAndNote: 'Güncelle ve Notu Ekle',
    btnContinueWithoutNote: 'Notsuz Devam Et',

    // Takvim
    calAddEvent: 'Etkinlik Ekle',
    calTitle: 'Başlık',
    calDate: 'Tarih',
    calTime: 'Saat',
    calType: 'Tür',
    calTypeBootcamp: 'Bootcamp / Eğitim',
    calTypeInterview: 'Mülakat / Sınav',
    calTypeMeeting: 'Toplantı',
    calTypeDeadline: 'Teslim Tarihi (Deadline)',
    calRecurring: 'Haftalık Tekrarla 🔁',
    calWeeks: 'Kaç hafta sürecek?',
    calSaveEvent: 'Etkinliği Kaydet',

    // Ajanda Sayfası
    agendaTitle: 'Günlük Planlayıcı',
    agendaSubtitle: 'Bugün neler yapıyoruz?',
    agendaTodoTitle: 'Yapılacaklar',
    agendaInCalendar: 'Takviminde Var',
    agendaDefaultEvent: 'Takvim Etkinliği',
    agendaAddToList: 'Listeye Ekle',
    agendaNewTodoPlaceholder: 'Yeni bir görev ekle...',
    agendaNoTodo: 'Henüz bir görev eklenmedi.',
    agendaDailyMood: 'Günün Modu',
    agendaNotesTitle: 'Çalışma Notları & Günlük',
    agendaSaved: 'Kaydedildi!',
    agendaNotesPlaceholder: 'Bugün neler öğrendin? Neler yaptın? Buraya yazabilirsin...',
    agendaFetchError: 'Ajanda verisi çekilirken hata oluştu:',
    agendaSaveLog: 'Ajanda kaydedilirken hata:',
    msgAgendaSaveError: 'Kaydedilirken bir hata oluştu!',

    // Gelişim Sayfası & Modallar
    devTitle: 'Gelişim Alanı',
    devSubtitle: 'Öğrenme yolculuğun ve becerilerin 🚀',
    devAddCourse: 'Eğitim Ekle',
    devAddProject: 'Proje Ekle',
    devAddSkill: 'Yetenek Ekle',
    devInProgress: 'Devam Eden Eğitimler',
    devProjects: 'Projeler',
    devTargetSkills: 'Hedeflenen Yetenekler',
    devChartTitle: 'Gelişim Çizelgesi',
    devChartSubtitle: 'Aylık öğrenme ve gelişim istatistikleri',
    
    modalAddCourse: 'Yeni Eğitim Ekle',
    modalAddProject: 'Yeni Proje Ekle',
    modalAddSkill: 'Yeni Yetenek Ekle',
    
    formCourseName: 'Eğitim / Kurs Adı',
    formCoursePlatform: 'Platform (Udemy, YouTube vb.)',
    formCourseProgress: 'İlerleme Yüzdesi (%)',
    formCourseStatus: 'Durum',
    statusInProgress: 'Devam Ediyor',
    statusCompleted: 'Tamamlandı',
    
    formProjectName: 'Proje Adı',
    formProjectTech: 'Kullanılan Teknolojiler (React, Java vb.)',
    formProjectStatus: 'Durum',
    
    formSkillName: 'Yetenek / Teknoloji Adı',
    formSkillLevel: 'Seviye (%)',

    // Profil Sayfası
    profileTabPersonal: 'Kişisel Bilgiler',
    profileTabResume: 'Eğitim & Deneyim',
    profileTabSecurity: 'Güvenlik & Şifre',
    profileDetails: 'Profil Detayları',
    profileFirstName: 'Ad',
    profileLastName: 'Soyad',
    profileEmailReadOnly: 'E-Posta (Salt Okunur)',
    profilePhone: 'Telefon',
    profileLocation: 'Konum',
    profileTitle: 'Ünvan',
    profileBio: 'Hakkımda',
    profileSaveSuccess: 'Profil başarıyla güncellendi!',
    profileSaveError: 'Profil kaydedilemedi:',
    resumeDataTitle: 'CV Bilgileri',
    resumeDataDesc: 'Buraya eklediğiniz eğitim ve deneyim bilgileri, CV oluşturucuda otomatik olarak yer alacaktır.',
    emailChangeTitle: 'E-Posta Değiştir',
    emailChangeDesc: 'E-postanızı değiştirmek için güvenlik amacıyla mevcut şifrenizi girmelisiniz.',
    emailNew: 'Yeni E-Posta',
    emailCurrentPass: 'Mevcut Şifre (Onay İçin)',
    btnUpdateEmail: 'E-Postayı Güncelle',
    emailChangeConfirm: 'E-posta adresinizi değiştirmek istediğinize emin misiniz?',
    emailChangeSuccess: 'E-posta değişti! Lütfen yeniden giriş yapın...',
    passChangeTitle: 'Şifre Değiştir',
    passChangeDesc: 'Hesap güvenliğiniz için güçlü bir şifre seçin.',
    passCurrent: 'Mevcut Şifre',
    passNew: 'Yeni Şifre',
    passNewConfirm: 'Yeni Şifre (Tekrar)',
    btnUpdatePass: 'Şifreyi Güncelle',
    passChangeSuccess: 'Şifre başarıyla değiştirildi!',
    passMismatch: 'Yeni şifreler eşleşmiyor!',
    profileCompany: 'Şirket',
    profilePosition: 'Pozisyon',
    profileStartDate: 'Başlangıç (Örn: Oca 2024)',
    profileEndDate: 'Bitiş (Örn: Devam Ediyor)',
    profileDesc: 'Açıklama (Ne yaptınız?)',
    profileSchool: 'Okul / Üniversite',
    profileDegree: 'Bölüm / Derece',
    profileGpa: 'GPA (Ops)',
    profileStartYear: 'Başlangıç (Yıl)',
    profileEndYear: 'Bitiş (Yıl)',
    noExperience: 'Henüz deneyim eklenmedi.',
    noEducation: 'Henüz eğitim eklenmedi.',

    // Resume (Özgeçmiş) Sayfası
    resumeControlTitle: 'CV Kontrolü',
    resumeLanguage: 'Dil',
    btnDownloadPDF: 'PDF İndir',
    resumeInfoWarning: 'Kişisel bilgileriniz, eğitim ve deneyiminiz otomatik olarak Profil ayarlarınızdan çekilmektedir. Değiştirmek isterseniz Profil sayfasına gidiniz.',
    resumeAddToCv: "Pebble'dan CV'ye Ekle",
    resumeShowProjects: 'Projelerimi Göster',
    resumeShowCerts: 'Sertifikalarımı Göster',
    resumeShowSkills: 'Yeteneklerimi Göster',
    resumeDefaultTitle: 'Meslek Ünvanı'
  },
  en: {
    menuDashboard: 'Dashboard',
    menuTracker: 'Tracker',
    menuAgenda: 'Agenda',
    menuCalendar: 'Calendar',
    menuDev: 'Development',
    menuResume: 'Resume',
    
    statTotal: 'Applied',
    statInterview: 'Interview',
    statAssessment: 'Assessment',
    statVideo: 'Video Interview',
    statOffer: 'Offer',
    calendarTitle: 'Calendar',
    reminderTitle: 'Reminder',
    dashStreak: 'Daily Streak',
    dashStreakMsg: 'Come back tomorrow to keep it going!',
    dashNoEvent: 'No events planned for today. A quiet day! ☕',

    myAccount: 'MY ACCOUNT',
    loggedInAs: 'LOGGED IN AS',
    profile: 'My Profile',
    settings: 'Settings',
    logout: 'Logout',
    comingSoon: 'This feature is coming soon!',
    defaultUser: 'User',

    navHome: 'Home',
    navAbout: 'About',
    navBlog: 'Blog',
    navContact: 'Contact',
    navRegister: 'Sign Up',
    navLogin: 'Sign In',
    heroTitlePart1: 'Little Pebbles, ',
    heroTitleHighlight: 'Big Dreams.',
    heroSubtitle: 'Track your job applications, interviews, trainings, and all career processes from a single place, stress-free and organized.',
    getStartedBtn: 'Get Started 🚀',
    aboutTitle: 'What is Pebble?',
    aboutText: 'Pebble is a smart tracking system that turns the complex and stressful period of job searching and career development into a fluffy and organized adventure. Instead of confining your applications to a spreadsheet, it combines your interviews, calendar, and notes on a single live screen.',
    blogTitle: 'Career Blog',
    blogText: 'Interview tactics, resume preparation secrets, and great tips to guide your career will be here very soon!',
    contactTitle: 'Contact Us',
    contactText: 'Have a problem? Or just want to say hi? We at the Pebble team are looking forward to your messages.',

    regTitle: 'Join Us ✨',
    regFirstName: 'First Name',
    regLastName: 'Last Name',
    regEmail: 'Email',
    regPassword: 'Password',
    regConfirmPassword: 'Confirm Password',
    regBtn: 'Sign Up',
    regHasAccount: 'Already have an account? Sign In',
    msgRegSuccess: 'Registration Successful! 🎉',
    msgEmailInUse: 'This email is already in use! Please sign in.',
    msgPassMismatch: 'Passwords do not match!',
    msgRegFailed: 'Registration Failed!',
    msgPassRules: 'Please follow the password rules!',
    passRulesTitle: 'Password Rules:',
    passRule1: 'Must be at least 8 characters long.',
    passRule2: 'Must contain at least one uppercase letter and one number.',
    passRule3: 'Must contain at least one special character (!@#$ etc.).',
    
    loginTitle: 'Welcome Back ✨',
    loginBtn: 'Sign In',
    forgotPass: 'Forgot Password?',
    loginOr: 'OR',
    loginGoogle: 'Sign in with Google',
    loginNoAccount: "Don't have an account? Sign Up",
    msgLoginFailed: 'Login Failed! Please check your credentials.',
    msgLoginSuccess: 'Login Successful! Redirecting...',
    
    forgotPassTitle: 'Forgot Password? 🥺',
    forgotPassDesc: 'Do not worry, you can set a new password and get your data back.',
    forgotNewPass: 'New Password',
    forgotConfirmPass: 'Confirm New Password',
    btnResetPass: 'Update Password',
    msgPassResetSuccess: 'Password updated successfully! 🎉',

    dashTitle: 'My Applications',
    dashSubtitle: 'All steps of your career journey are here ✨',
    addNew: '+ Add New',
    loading: 'LOADING...',
    emptyList: 'No records yet. Start your career journey!',
    colCompany: 'COMPANY',
    colPosition: 'POSITION',
    colLocMode: 'LOCATION & MODE',
    colSalary: 'SALARY',
    colStage: 'STAGE',
    colAction: 'ACTION',
    btnView: 'View',
    unspecified: 'Unspecified',
    
    confirmDelete: 'Are you sure you want to delete this record?',
    errorLog: 'Error',
    userInfoError: 'Could not fetch user info',
    statusApplied: 'Applied',
    statusAssessment: 'Assessment',
    statusVideo: 'Video Interview',
    statusInterview: 'Interview',
    statusOffer: 'Offer',
    statusRejected: 'Rejected',

    btnCancel: 'Cancel',
    btnSave: 'Save',
    btnUpdating: 'Updating...',

    newAppTitle: 'New Application Record',
    formCompany: 'Company / Org Name',
    formPosition: 'Position / Program Name',
    formCategory: 'Category',
    catJob: 'Job Application',
    catInternship: 'Internship',
    catBootcamp: 'Bootcamp',
    catWebinar: 'Webinar',
    catOther: 'Other',
    formPlatform: 'Platform',
    platCompanySite: 'Company Website',
    platOther: 'Other (URL/Name)',
    platPlaceholder: 'Site name or URL...',
    formSalaryStatus: 'Salary / Wage Status',
    salUnknown: 'Unknown',
    salVolunteer: 'Volunteer (Unpaid)',
    salSpecific: 'Specify Amount...',
    formAmount: 'Amount',
    salPlaceholder: 'e.g. 45.000 TL',
    formWorkMode: 'Work Mode',
    modeRemote: 'Remote',
    modeHybrid: 'Hybrid',
    modeOnsite: 'Onsite',
    formLocation: 'Location',
    locPlaceholder: 'City/Country',
    formDate: 'Date',
    formQuestions: 'Application Form Questions & Answers',
    questionsPlaceholder: 'Note your answers to form questions like years of exp, technical questions here...',
    formDescription: 'Job Description',
    descPlaceholder: 'You can paste the job description here...',

    oldNote: 'Old Note',
    detailPlatform: 'Platform',
    detailUnspecified: 'Unspecified',
    detailSalary: 'Salary',
    detailMode: 'Mode',
    detailLocation: 'Location',
    detailNotSpecified: 'Not Specified',
    detailQuestions: 'My Application Form Info',
    detailDescription: 'Job Description',
    detailJournal: 'Process Journal',
    journalPlaceholder: 'What happened at this stage? Add your notes...',
    btnAddJournal: 'Add to Journal',
    emptyJournal: 'No journal entry has been made yet.',

    statusUpdating: 'Updating Stage',
    newStatusLabel: 'New status:',
    statusNotePrompt: 'Would you like to add a note regarding this change?',
    statusNotePlaceholder: 'e.g. Received technical test email, scheduled for next Tuesday...',
    btnUpdateAndNote: 'Update and Add Note',
    btnContinueWithoutNote: 'Continue Without Note',

    calAddEvent: 'Add Event',
    calTitle: 'Title',
    calDate: 'Date',
    calTime: 'Time',
    calType: 'Type',
    calTypeBootcamp: 'Bootcamp / Training',
    calTypeInterview: 'Interview / Exam',
    calTypeMeeting: 'Meeting',
    calTypeDeadline: 'Deadline',
    calRecurring: 'Repeat Weekly 🔁',
    calWeeks: 'How many weeks?',
    calSaveEvent: 'Save Event',

    agendaTitle: 'Daily Planner',
    agendaSubtitle: 'What are we doing today?',
    agendaTodoTitle: 'To-Do List',
    agendaInCalendar: 'In Your Calendar',
    agendaDefaultEvent: 'Calendar Event',
    agendaAddToList: 'Add to List',
    agendaNewTodoPlaceholder: 'Add a new task...',
    agendaNoTodo: 'No tasks added yet.',
    agendaDailyMood: 'Mood of the Day',
    agendaNotesTitle: 'Study Notes & Journal',
    agendaSaved: 'Saved!',
    agendaNotesPlaceholder: 'What did you learn today? What did you do? You can write it here...',
    agendaFetchError: 'Error fetching agenda data:',
    agendaSaveLog: 'Error saving agenda:',
    msgAgendaSaveError: 'An error occurred while saving!',

    devTitle: 'Development Area',
    devSubtitle: 'Your learning journey and skills 🚀',
    devAddCourse: 'Add Course',
    devAddProject: 'Add Project',
    devAddSkill: 'Add Skill',
    devInProgress: 'In Progress Courses',
    devProjects: 'Projects',
    devTargetSkills: 'Target Skills',
    devChartTitle: 'Development Chart',
    devChartSubtitle: 'Monthly learning and development statistics',

    modalAddCourse: 'Add New Course',
    modalAddProject: 'Add New Project',
    modalAddSkill: 'Add New Skill',
    
    formCourseName: 'Course Name',
    formCoursePlatform: 'Platform (Udemy, YouTube etc.)',
    formCourseProgress: 'Progress (%)',
    formCourseStatus: 'Status',
    statusInProgress: 'In Progress',
    statusCompleted: 'Completed',
    
    formProjectName: 'Project Name',
    formProjectTech: 'Technologies Used (React, Java etc.)',
    formProjectStatus: 'Status',
    
    formSkillName: 'Skill / Tech Name',
    formSkillLevel: 'Level (%)',

    profileTabPersonal: 'Personal Info',
    profileTabResume: 'Resume Data',
    profileTabSecurity: 'Security & Password',
    profileDetails: 'Profile Details',
    profileFirstName: 'First Name',
    profileLastName: 'Last Name',
    profileEmailReadOnly: 'Email (Read Only)',
    profilePhone: 'Phone',
    profileLocation: 'Location',
    profileTitle: 'Title',
    profileBio: 'Bio',
    profileSaveSuccess: 'Profile updated successfully!',
    profileSaveError: 'Failed to save profile:',
    resumeDataTitle: 'Resume Data',
    resumeDataDesc: 'Education and experience added here will automatically appear in your resume.',
    emailChangeTitle: 'Change Email',
    emailChangeDesc: 'You must enter your current password to change your email.',
    emailNew: 'New Email',
    emailCurrentPass: 'Current Password (To Confirm)',
    btnUpdateEmail: 'Update Email',
    emailChangeConfirm: 'Are you sure you want to change your email address?',
    emailChangeSuccess: 'Email changed! Please login again...',
    passChangeTitle: 'Change Password',
    passChangeDesc: 'Choose a strong password for your account security.',
    passCurrent: 'Current Password',
    passNew: 'New Password',
    passNewConfirm: 'Confirm New Password',
    btnUpdatePass: 'Update Password',
    passChangeSuccess: 'Password changed successfully!',
    passMismatch: 'New passwords do not match!',
    profileCompany: 'Company',
    profilePosition: 'Position',
    profileStartDate: 'Start Date (e.g., Jan 2024)',
    profileEndDate: 'End Date (e.g., Present)',
    profileDesc: 'Description (What did you do?)',
    profileSchool: 'School / University',
    profileDegree: 'Degree / Major',
    profileGpa: 'GPA (Optional)',
    profileStartYear: 'Start Year',
    profileEndYear: 'End Year',
    noExperience: 'No experience added yet.',
    noEducation: 'No education added yet.',

    resumeControlTitle: 'CV Control',
    resumeLanguage: 'Language',
    btnDownloadPDF: 'Download PDF',
    resumeInfoWarning: 'Your personal info, education, and experience are automatically fetched from your Profile. Go to the Profile page to edit.',
    resumeAddToCv: 'Add from Pebble to CV',
    resumeShowProjects: 'Show My Projects',
    resumeShowCerts: 'Show My Certificates',
    resumeShowSkills: 'Show My Skills',
    resumeDefaultTitle: 'Job Title'
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(localStorage.getItem('app_lang') || 'tr');

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const toggleLanguage = () => {
    const newLang = language === 'tr' ? 'en' : 'tr';
    setLanguage(newLang);
    localStorage.setItem('app_lang', newLang);
  };

  const t = (key) => translations[language][key] || key;

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);