import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

const translations = {
  tr: {
    // Menü
    menuDashboard: 'Dashboard',
    menuTracker: 'Tracker',
    menuAgenda: 'Ajanda',
    menuCalendar: 'Takvim',
    menuDev: 'Gelişim',
    menuResume: 'Resume',
    
    // Dashboard (İstatistikler)
    statTotal: 'Başvurulan',
    statInterview: 'Mülakat',
    statAssessment: 'Teknik Sınav',
    statVideo: 'Video Mülakat',
    statOffer: 'Kabul',
    calendarTitle: 'Takvim',
    reminderTitle: 'Hatırlatıcı',

    // Topbar
    myAccount: 'HESABIM',
    loggedInAs: 'GİRİŞ YAPILAN HESAP',
    profile: 'Profilim',
    settings: 'Ayarlar',
    logout: 'Çıkış Yap',
    comingSoon: 'Bu özellik yakında eklenecek!',
    defaultUser: 'Kullanıcı',
    
    // Karşılama Sayfası
    navHome: 'Ana Sayfa',
    navAbout: 'Hakkında',
    navBlog: 'Blog',
    navContact: 'İletişim',
    navRegister: 'Kayıt Ol',
    navLogin: 'Giriş Yap',
    heroTitlePart1: 'Minik Adımlar, ',
    heroTitleHighlight: 'Büyük Hayaller.',
    heroSubtitle: 'İş başvurularını, mülakatlarını, eğitimlerini ve tüm kariyer süreçlerini tek bir yerden, stressiz ve düzenli bir şekilde takip et.',
    getStartedBtn: 'Hemen Başla 🚀',
    aboutTitle: 'Pebble Nedir?',
    aboutText: 'Pebble, iş arama ve kariyer gelişimi sürecindeki o karmaşık ve stresli dönemi, pofuduk ve düzenli bir serüvene dönüştüren akıllı bir takip sistemidir. Başvurularını bir tabloya hapsetmek yerine; mülakatlarını, takvimini ve notlarını tek bir canlı ekranda birleştirir.',
    blogTitle: 'Kariyer Blogu',
    blogText: 'Mülakat taktikleri, özgeçmiş hazırlama sırları ve kariyerine yön verecek harika ipuçları çok yakında burada olacak!',
    contactTitle: 'Bize Ulaşın',
    contactText: 'Bir sorun mu var? Veya sadece selam mı vermek istiyorsun? Pebble ekibi olarak mesajlarını sabırsızlıkla bekliyoruz.',

    // Kayıt (Register) Sayfası
    regTitle: 'Aramıza Katıl ✨',
    regFirstName: 'Ad',
    regLastName: 'Soyad',
    regEmail: 'Mail',
    regPassword: 'Şifre',
    regConfirmPassword: 'Şifreyi Tekrar Gir',
    regBtn: 'Kayıt Ol',
    regHasAccount: 'Hesabın var mı? Giriş Yap',
    msgRegSuccess: 'Kayıt Başarılı! 🎉',
    msgEmailInUse: 'Bu mail zaten kullanımda! Giriş yap.',
    msgPassMismatch: 'Şifreler eşleşmiyor!',
    msgRegFailed: 'Kayıt Başarısız!',
    msgPassRules: 'Lütfen şifre kurallarına uyun!',
    passRulesTitle: 'Şifre Kuralları:',
    passRule1: 'En az 8 karakter uzunluğunda olmalı.',
    passRule2: 'En az bir büyük harf ve bir rakam içermeli.',
    passRule3: 'En az bir özel karakter (!@#$ vb.) içermeli.',

    // Tracker Tablo
    dashTitle: 'Başvurularım',
    dashSubtitle: 'Kariyer yolculuğundaki tüm adımların burada ✨',
    addNew: '+ Yeni Ekle',
    loading: 'YÜKLENİYOR...',
    emptyList: 'Henüz bir kayıt yok. Kariyer serüvenine başla!',
    colCompany: 'KURUM',
    colPosition: 'POZİSYON',
    colLocMode: 'LOKASYON & MOD',
    colSalary: 'MAAŞ',
    colStage: 'AŞAMA',
    colAction: 'İŞLEM',
    btnView: 'Görüntüle',
    unspecified: 'Belirtilmedi',
    
    // Uyarılar ve Başvuru Durumları
    confirmDelete: 'Bu kaydı silmek istediğine emin misin?',
    errorLog: 'Hata',
    userInfoError: 'Kullanıcı bilgisi alınamadı',
    statusApplied: 'Başvuruldu',
    statusAssessment: 'Teknik Sınav',
    statusVideo: 'Video Mülakat',
    statusInterview: 'Görüşme',
    statusOffer: 'Kabul',
    statusRejected: 'Red',

    // Modallar Ortak
    btnCancel: 'İptal',
    btnSave: 'Kaydet',
    btnUpdating: 'Güncelleniyor...',

    // Form Modalı
    newAppTitle: 'Yeni Başvuru Kaydı',
    formCompany: 'Kurum / Şirket Adı',
    formPosition: 'Pozisyon / Program Adı',
    formCategory: 'Kategori',
    catJob: 'İş Başvurusu',
    catInternship: 'Staj',
    catBootcamp: 'Bootcamp',
    catWebinar: 'Webinar',
    catOther: 'Diğer',
    formPlatform: 'Platform',
    platCompanySite: 'Şirket Sitesi',
    platOther: 'Diğer (URL/Ad Belirt)',
    platPlaceholder: 'Site adı veya URL...',
    formSalaryStatus: 'Maaş / Ücret Durumu',
    salUnknown: 'Bilinmiyor',
    salVolunteer: 'Gönüllü (Ücretsiz)',
    salSpecific: 'Tutar Belirt...',
    formAmount: 'Miktar',
    salPlaceholder: 'Örn: 45.000 TL',
    formWorkMode: 'Çalışma Modeli',
    modeRemote: 'Remote',
    modeHybrid: 'Hybrid',
    modeOnsite: 'Ofis',
    formLocation: 'Lokasyon',
    locPlaceholder: 'Şehir/Ülke',
    formDate: 'Tarih',
    formQuestions: 'Başvuru Formu Soruları & Cevaplarım',
    questionsPlaceholder: 'Deneyim yılı, teknik sorular vb. formda ne cevap verdiğini buraya not et...',
    formDescription: 'İlan Detayları',
    descPlaceholder: 'İş tanımını buraya yapıştırabilirsin...',

    // Detay Modalı
    oldNote: 'Eski Not',
    detailPlatform: 'Platform',
    detailUnspecified: 'Belirsiz',
    detailSalary: 'Maaş',
    detailMode: 'Mod',
    detailLocation: 'Lokasyon',
    detailNotSpecified: 'Belirtilmedi',
    detailQuestions: 'Başvuru Formu Bilgilerim',
    detailDescription: 'İş Tanımı',
    detailJournal: 'Süreç Günlüğü',
    journalPlaceholder: 'Bu aşamada neler oldu? Notlarını ekle...',
    btnAddJournal: 'Günlüğe Ekle',
    emptyJournal: 'Henüz bir günlük girişi yapılmamış.',

    // Statü Modalı
    statusUpdating: 'Aşama Güncelleniyor',
    newStatusLabel: 'Yeni statü:',
    statusNotePrompt: 'Bu değişiklikle ilgili bir not eklemek ister misin?',
    statusNotePlaceholder: 'Örn: Teknik sınav maili geldi, haftaya Salı günü için randevulaştık...',
    btnUpdateAndNote: 'Güncelle ve Notu Ekle',
    btnContinueWithoutNote: 'Notsuz Devam Et',
  },
  en: {
    menuDashboard: 'Dashboard',
    menuTracker: 'Tracker',
    menuAgenda: 'Agenda',
    menuCalendar: 'Calendar',
    menuDev: 'Development',
    menuResume: 'Resume',
    
    statTotal: 'Applied',
    statInterview: 'Interview',
    statAssessment: 'Assessment',
    statVideo: 'Video Interview',
    statOffer: 'Offer',
    calendarTitle: 'Calendar',
    reminderTitle: 'Reminder',

    myAccount: 'MY ACCOUNT',
    loggedInAs: 'LOGGED IN AS',
    profile: 'My Profile',
    settings: 'Settings',
    logout: 'Logout',
    comingSoon: 'This feature is coming soon!',
    defaultUser: 'User',

    // Landing Page
    navHome: 'Home',
    navAbout: 'About',
    navBlog: 'Blog',
    navContact: 'Contact',
    navRegister: 'Sign Up',
    navLogin: 'Sign In',
    heroTitlePart1: 'Little Pebbles, ',
    heroTitleHighlight: 'Big Dreams.',
    heroSubtitle: 'Track your job applications, interviews, trainings, and all career processes from a single place, stress-free and organized.',
    getStartedBtn: 'Get Started 🚀',
    aboutTitle: 'What is Pebble?',
    aboutText: 'Pebble is a smart tracking system that turns the complex and stressful period of job searching and career development into a fluffy and organized adventure. Instead of confining your applications to a spreadsheet, it combines your interviews, calendar, and notes on a single live screen.',
    blogTitle: 'Career Blog',
    blogText: 'Interview tactics, resume preparation secrets, and great tips to guide your career will be here very soon!',
    contactTitle: 'Contact Us',
    contactText: 'Have a problem? Or just want to say hi? We at the Pebble team are looking forward to your messages.',

    // Kayıt (Register) Sayfası
    regTitle: 'Join Us ✨',
    regFirstName: 'First Name',
    regLastName: 'Last Name',
    regEmail: 'Email',
    regPassword: 'Password',
    regConfirmPassword: 'Confirm Password',
    regBtn: 'Sign Up',
    regHasAccount: 'Already have an account? Sign In',
    msgRegSuccess: 'Registration Successful! 🎉',
    msgEmailInUse: 'This email is already in use! Please sign in.',
    msgPassMismatch: 'Passwords do not match!',
    msgRegFailed: 'Registration Failed!',
    msgPassRules: 'Please follow the password rules!',
    passRulesTitle: 'Password Rules:',
    passRule1: 'Must be at least 8 characters long.',
    passRule2: 'Must contain at least one uppercase letter and one number.',
    passRule3: 'Must contain at least one special character (!@#$ etc.).',
    
    dashTitle: 'My Applications',
    dashSubtitle: 'All steps of your career journey are here ✨',
    addNew: '+ Add New',
    loading: 'LOADING...',
    emptyList: 'No records yet. Start your career journey!',
    colCompany: 'COMPANY',
    colPosition: 'POSITION',
    colLocMode: 'LOCATION & MODE',
    colSalary: 'SALARY',
    colStage: 'STAGE',
    colAction: 'ACTION',
    btnView: 'View',
    unspecified: 'Unspecified',
    
    confirmDelete: 'Are you sure you want to delete this record?',
    errorLog: 'Error',
    userInfoError: 'Could not fetch user info',
    statusApplied: 'Applied',
    statusAssessment: 'Assessment',
    statusVideo: 'Video Interview',
    statusInterview: 'Interview',
    statusOffer: 'Offer',
    statusRejected: 'Rejected',

    btnCancel: 'Cancel',
    btnSave: 'Save',
    btnUpdating: 'Updating...',

    newAppTitle: 'New Application Record',
    formCompany: 'Company / Org Name',
    formPosition: 'Position / Program Name',
    formCategory: 'Category',
    catJob: 'Job Application',
    catInternship: 'Internship',
    catBootcamp: 'Bootcamp',
    catWebinar: 'Webinar',
    catOther: 'Other',
    formPlatform: 'Platform',
    platCompanySite: 'Company Website',
    platOther: 'Other (URL/Name)',
    platPlaceholder: 'Site name or URL...',
    formSalaryStatus: 'Salary / Wage Status',
    salUnknown: 'Unknown',
    salVolunteer: 'Volunteer (Unpaid)',
    salSpecific: 'Specify Amount...',
    formAmount: 'Amount',
    salPlaceholder: 'e.g. 45.000 TL',
    formWorkMode: 'Work Mode',
    modeRemote: 'Remote',
    modeHybrid: 'Hybrid',
    modeOnsite: 'Onsite',
    formLocation: 'Location',
    locPlaceholder: 'City/Country',
    formDate: 'Date',
    formQuestions: 'Application Form Questions & Answers',
    questionsPlaceholder: 'Note your answers to form questions like years of exp, technical questions here...',
    formDescription: 'Job Description',
    descPlaceholder: 'You can paste the job description here...',

    oldNote: 'Old Note',
    detailPlatform: 'Platform',
    detailUnspecified: 'Unspecified',
    detailSalary: 'Salary',
    detailMode: 'Mode',
    detailLocation: 'Location',
    detailNotSpecified: 'Not Specified',
    detailQuestions: 'My Application Form Info',
    detailDescription: 'Job Description',
    detailJournal: 'Process Journal',
    journalPlaceholder: 'What happened at this stage? Add your notes...',
    btnAddJournal: 'Add to Journal',
    emptyJournal: 'No journal entry has been made yet.',

    statusUpdating: 'Updating Stage',
    newStatusLabel: 'New status:',
    statusNotePrompt: 'Would you like to add a note regarding this change?',
    statusNotePlaceholder: 'e.g. Received technical test email, scheduled for next Tuesday...',
    btnUpdateAndNote: 'Update and Add Note',
    btnContinueWithoutNote: 'Continue Without Note',
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(localStorage.getItem('app_lang') || 'tr');

  const toggleLanguage = () => {
    const newLang = language === 'tr' ? 'en' : 'tr';
    setLanguage(newLang);
    localStorage.setItem('app_lang', newLang);
  };

  const t = (key) => translations[language][key] || key;

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);